"""Phase 2: AP (vendors, bills, POs, vendor payments) + tax rates

Revision ID: 0ffa398f375c
Revises: b0ec25722ff3
Create Date: 2026-07-15 20:20:06.520879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffa398f375c'
down_revision = 'b0ec25722ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_rates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('vendors',
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('default_expense_account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['default_expense_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bills',
    sa.Column('vendor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('terms', sa.String(length=200), nullable=True),
    sa.Column('approved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bills_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('vendor_contacts',
    sa.Column('vendor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_contacts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_contacts_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('vendor_payments',
    sa.Column('vendor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cash_account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['cash_account_id'], ['cash_accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_payments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_payments_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('bill_lines',
    sa.Column('bill_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_lines_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_lines_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('vendor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('po_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('converted_bill_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['converted_bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'po_number', name='uq_purchase_orders_tenant_number')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('vendor_payment_applications',
    sa.Column('vendor_payment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bill_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vendor_payment_id'], ['vendor_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_payment_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_payment_applications_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_payment_applications_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_payment_applications_vendor_payment_id'), ['vendor_payment_id'], unique=False)

    op.create_table('purchase_order_lines',
    sa.Column('purchase_order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_purchase_order_id'), ['purchase_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_vendor_payment_id', sa.UUID(as_uuid=False), nullable=True))
        batch_op.create_foreign_key(None, 'vendor_payments', ['related_vendor_payment_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate_id', sa.UUID(as_uuid=False), nullable=True))
        batch_op.add_column(sa.Column('tax_rate_pct', sa.Numeric(precision=6, scale=4), nullable=False, server_default='0'))
        batch_op.create_foreign_key(None, 'tax_rates', ['tax_rate_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tax_rate_pct')
        batch_op.drop_column('tax_rate_id')

    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('related_vendor_payment_id')

    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_purchase_order_id'))

    op.drop_table('purchase_order_lines')
    with op.batch_alter_table('vendor_payment_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_payment_applications_vendor_payment_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_payment_applications_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_payment_applications_bill_id'))

    op.drop_table('vendor_payment_applications')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_tenant_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('bill_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_lines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bill_lines_bill_id'))

    op.drop_table('bill_lines')
    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_payments_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_payments_tenant_id'))

    op.drop_table('vendor_payments')
    with op.batch_alter_table('vendor_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_contacts_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_contacts_tenant_id'))

    op.drop_table('vendor_contacts')
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_bills_tenant_id'))

    op.drop_table('bills')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_tenant_id'))

    op.drop_table('vendors')
    with op.batch_alter_table('tax_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_rates_tenant_id'))

    op.drop_table('tax_rates')
    # ### end Alembic commands ###
