"""Add email_connections table for Phase 9 integrations

Revision ID: 1d49b761624b
Revises: eb6e8c0e9753
Create Date: 2026-07-16 19:58:59.125838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d49b761624b'
down_revision = 'eb6e8c0e9753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_connections',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'provider', name='uq_email_connections_tenant_user_provider')
    )
    with op.batch_alter_table('email_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_connections_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_connections_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_connections_tenant_id'))

    op.drop_table('email_connections')
    # ### end Alembic commands ###
