"""Phase 6: order tracking (shipments)

Revision ID: 26c8f0b31778
Revises: 3246b689dad0
Create Date: 2026-07-16 18:39:59.462946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c8f0b31778'
down_revision = '3246b689dad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('reference_type', sa.String(length=20), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=False),
    sa.Column('carrier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_source', sa.String(length=20), nullable=False),
    sa.Column('status_note', sa.String(length=500), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_reference_type'))
        batch_op.drop_index(batch_op.f('ix_shipments_reference_id'))

    op.drop_table('shipments')
    # ### end Alembic commands ###
