"""Phase 5: transportation (vehicles, drivers, loads)

Revision ID: 3246b689dad0
Revises: 3ab1ae6fcb5f
Create Date: 2026-07-16 18:33:20.465553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3246b689dad0'
down_revision = '3ab1ae6fcb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('license_class', sa.String(length=10), nullable=True),
    sa.Column('license_expiration', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('vehicles',
    sa.Column('unit_number', sa.String(length=30), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'unit_number', name='uq_vehicles_tenant_unit_number')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('loads',
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('load_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('driver_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('origin', sa.String(length=300), nullable=True),
    sa.Column('destination', sa.String(length=300), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('base_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('converted_invoice_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['converted_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'load_number', name='uq_loads_tenant_number')
    )
    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loads_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loads_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('load_charges',
    sa.Column('load_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('load_charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_load_charges_load_id'), ['load_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_load_charges_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('load_charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_load_charges_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_load_charges_load_id'))

    op.drop_table('load_charges')
    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loads_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_loads_customer_id'))

    op.drop_table('loads')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_tenant_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_tenant_id'))

    op.drop_table('drivers')
    # ### end Alembic commands ###
