"""Phase 4: work orders

Revision ID: 3ab1ae6fcb5f
Revises: 636e6ef15a61
Create Date: 2026-07-16 15:19:04.248832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab1ae6fcb5f'
down_revision = '636e6ef15a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('wo_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('converted_invoice_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['converted_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'wo_number', name='uq_work_orders_tenant_number')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('work_order_lines',
    sa.Column('work_order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('line_type', sa.String(length=10), nullable=False),
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_lines_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_lines_work_order_id'), ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_lines_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_lines_tenant_id'))

    op.drop_table('work_order_lines')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_customer_id'))

    op.drop_table('work_orders')
    # ### end Alembic commands ###
