"""Phase 3: inventory control (items, locations, stock)

Revision ID: 636e6ef15a61
Revises: 0ffa398f375c
Create Date: 2026-07-15 21:34:48.205856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636e6ef15a61'
down_revision = '0ffa398f375c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('items',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('reorder_quantity', sa.Integer(), nullable=False),
    sa.Column('income_account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('expense_account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['income_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_items_tenant_sku')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('inventory_transactions',
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('stock_levels',
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'item_id', 'location_id', name='uq_stock_levels_item_location')
    )
    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_levels_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_levels_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_levels_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('bill_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.UUID(as_uuid=False), nullable=True))
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])

    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.UUID(as_uuid=False), nullable=True))
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.UUID(as_uuid=False), nullable=True))
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'])

    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.UUID(as_uuid=False), nullable=True))
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.UUID(as_uuid=False), nullable=True))
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('bill_lines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_levels_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_stock_levels_location_id'))
        batch_op.drop_index(batch_op.f('ix_stock_levels_item_id'))

    op.drop_table('stock_levels')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_location_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_item_id'))

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_tenant_id'))

    op.drop_table('items')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_tenant_id'))

    op.drop_table('locations')
    # ### end Alembic commands ###
