"""Add portal_users table for Phase 8 customer portal

Revision ID: eb6e8c0e9753
Revises: 89eed3482cd7
Create Date: 2026-07-16 19:34:47.780303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6e8c0e9753'
down_revision = '89eed3482cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_users',
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_portal_users_tenant_email')
    )
    with op.batch_alter_table('portal_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_users_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_users_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portal_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_portal_users_email'))
        batch_op.drop_index(batch_op.f('ix_portal_users_customer_id'))

    op.drop_table('portal_users')
    # ### end Alembic commands ###
